### ISSUE TITLE
Quick fix support

### ISSUE THREAD

**Issue by sonatard** [JetBrains/Qodana#26]
Do you have a  plan to quick fix by Qodana.
I want to exec quick fix in command line.

**Comment by a-kuznetsova** [comment]
Hi @sonatard,

We plan to support quick fixes in the near future. However, I am not sure if they will be applicable through command line.

I have duplicated your question to our issue tracker [QD-775](https://youtrack.jetbrains.com/issue/QD-775). If you would like to be notified about the further updates, add yourself as a watcher for the issue [QD-775](https://youtrack.jetbrains.com/issue/QD-775). Please be informed that the Github Issues section in this repository will be disabled as of April 5, 2021.

**Comment by tiulpin** [comment]
Already possible with 2023.2-eap https://www.jetbrains.com/help/qodana/2023.2/quick-fix.html
@sonatard

**Comment by sonatard** [comment]
Great!! 

But we got error exec `qodana scan` 

```
$ qodana scan
✓  Finished pulling the latest version of linter
2023/07/19 13:29:15 Sync IDEA cache from: /data/cache/.idea to: /data/project/.idea

Start Failed
Internal error. Please refer to https://jb.gg/ide/critical-startup-errors

java.nio.file.FileSystemException: /data/cache/idea/232/.port: Invalid argument
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
        at java.base/java.nio.file.Files.deleteIfExists(Files.java:1191)
        at com.intellij.idea.DirectoryLock.lockOrActivate(DirectoryLock.java:138)
        at com.intellij.idea.StartupUtil$lockSystemDirs$result$1.invokeSuspend(StartupUtil.kt:615)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

-----
Your JRE: 17.0.7+7-b1000.6 aarch64 (JetBrains s.r.o.)
/opt/idea/jbr
2023/07/19 13:29:16 Sync IDEA cache from: /data/project/.idea to: /data/cache/.idea
✗  Qodana exited with code 3

!  Check ./logs/ in the results directory for more information

?  Do you want to open /Users/sonatard/Library/Caches/JetBrains/Qodana/621eb3c4-c0ed5f6f/results [Y/n]: No
```
